# Generated by Django 3.1.3 on 2021-02-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='comment',
            field=models.CharField(default='comment', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishes',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
